### ISSUE TITLE
bind hjkl keys to move in historial

### ISSUE THREAD

**Issue by benalb** [dvorka/hstr#106]
As a vim user, would like to use jk instead of up and down. Also would change ctrl-/ ¿any easy way to do it?

**Comment by tbabej** [comment]
It's not configurable, but simple edition of src/hstr.c should do it. Search for KEY_UP and KEY_DOWN in loop_to_select's while cycle and replace it with appropriate values for J and K (you will have to define new constants).

**Comment by tbabej** [comment]
A similiar support was implemented for C-n and C-p. Using 'j' and 'k' would collide with adding input, so you would have to switch between 'normal' and 'insert' modes as in vim.

**Comment by dvorka** [comment]
> ...would like to use jk instead of up and down

I'm opened to introduce Vim key binding (additive or configurable), however, I cannot easily add jk (as Tomas just described). The reason is that list of history items is filtered as you type - including jk keys. This is also why all the control keys are bound to Ctrl- (I just added Ctrl-n and Ctrl-p keys to move up/down). Would you have any suggestion how should I solve this clash as there is nothing like read/rdwr mode? Can I close?

> Also would change ctrl-/

Any suggestion for alternative key binding?

**Comment by benalb** [comment]
Ctrl-n and p is fine for me.

For ctrl-/, it must be a problem with my keyboard layout: ctrl - / (ctrl +
caps + 7 for me) ends with / in the list of history, but ctrl - 7 works as
ctrl-/ would do (and, by the way, ctr-- works too)

2015-01-04 14:05 GMT+01:00 dvorka <notifications@github.com>:

> ...would like to use jk instead of up and down
>
> I'm opened to introduce Vim key binding (additive or configurable),
> however, I cannot easily add jk (as Tomas just described). The reason is
> that list of history items is filtered as you type - including jk keys.
> This is also why all the control keys are bound to Ctrl- (I just added
> Ctrl-n and Ctrl-p keys to move up/down). Would you have any suggestion how
> should I solve this clash as there is nothing like read/rdwr mode? Can I
> close?
>
> Also would change ctrl-/
>
> Any suggestion for alternative key binding?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dvorka/hstr/issues/106#issuecomment-68632208>.
>



-- 
signature: work in progress

**Comment by dvorka** [comment]
Conclusion: `Ctrl-7` to become alias for view rotation  (`Ctrl--` might be used/reserved by terminal/`hh` for resizing).

**Comment by livibetter** [comment]
@dvorka can we also have <kbd>Ctrl+J</kbd> and <kbd>Ctrl+K</kbd>, the <kbd>Ctrl+N</kbd> and <kbd>Ctrl+P</kbd> are a bit of awkward for Vim users IMHO, or maybe it's time for keybinding customization/configuration?

**Comment by nkoester** [comment]
livibetter:
> ...or maybe it's time for keybinding customization/configuration?

I think this would actually the best solution and the time for it ;)
