### ISSUE TITLE
Support homebrew

### ISSUE THREAD

**Issue by tobegit3hub** [dvorka/hstr#108]
Most of developers use homebrew rather than macport. It could be great to install hh with command `brew install hh`. And all we need to do is writing a hh.rb which looks like [this](https://github.com/tobegit3hub/homebrew-run).

**Comment by dvorka** [comment]
This makes a lot of sense. Unfortunately I'm not OS X user - could you help please?

**Comment by tobegit3hub** [comment]
I will help to support this and come back to this issue if I have something :smiley:

**Comment by tobegit3hub** [comment]
I have to say `brew install hh` is [well supported](https://github.com/Homebrew/homebrew/blob/664f79adfc88212754eb8642a31a290c3dc3991f/Library/Formula/hh.rb) and thanks these guys @atdt @jacknagel @BrewTestBot . What we need to do is sending pull-request after releasing new package :+1:

**Comment by tobegit3hub** [comment]
The usage for homebrew users is `brew install hh`. Please update the readme @dvorka
