### ISSUE TITLE
Support C-n and C-p to select command

### ISSUE THREAD

**Issue by tobegit3hub** [dvorka/hstr#109]
`hh` is the convenient tool which is like [tig](https://github.com/jonas/tig). It could be better to support the shortcuts of C-n and C-p so that I don't have to move my hands to select the commands :smiley:

**Comment by tbabej** [comment]
See my reply for  #106 .

**Comment by tobegit3hub** [comment]
It's nice that it's configurable for any developer. But I don't think I will edit the source code and compile for myself.

I had the same support of #106 but it affects the input to search. So C-n and C-p might be the best choice for us.

Feel free to close this if you don't wanna fix it. It's not a big deal :smile:

**Comment by tobegit3hub** [comment]
Great! Thanks @dvorka :+1:
