### ISSUE TITLE
README.md introduce zsh/... other shells documentation

### ISSUE THREAD

**Issue by tbabej** [dvorka/hstr#111]
About a month ago, I tried using different shell than bash (zsh). Although described procedure to rebind the C-r to hh did not work, hh command itself had no problem running in different shell.

I suggest we drop BASH mention from the readme, mabye replacing just by shell. Or mention that hh should be compatible with any shell that stores the history in the same format as bash does.

That way we would not scare off a potentional part of user base.

**Comment by dvorka** [comment]
Good point. I will try 'zsh' and possibly other shells and change the documentation accordingly.

**Comment by cleeland** [comment]
I wouldn't go that far. Zsh tries to be bash compatible where possible, but
there are many other shells which simply aren't: busybox, sh, ksh, csh,
tcsh, etc

I think there is benefit to being specific to not set incorrect
expectations. If you want to not scare people away, document the specific
features that hh expects from the shell.

**Comment by Heart1010** [comment]
I'm also using zsh now... so what do I have to do to use hstr with zsh? (bind CTRL+R to hh comand.... use .zsh_history instead of .bash_history....)

**Comment by dvorka** [comment]
Closing: Zsh and binding to key documented in CONFIGURATION.md + `hh --show-configuration` detects Zsh and shows the corresponding configuration.
