### ISSUE TITLE
Highlight the replacing entry after Deletion

### ISSUE THREAD

**Issue by livibetter** [dvorka/hstr#115]
I noticed the highlight is missing after you delete one entry. I can see the red message about the deleted entry, but green highlight is gone.

It would make sense if the currently selected entry is changed to none after a deletion, but if you press again right away, even no green highlight bar, you can see the one replaces the just-deleted entry's position is deleted. Press again, another takes the place is deleted, and so on.

I think this is a bug for not having the green highlight bar after deletion, if there is still entries to select. I'd like to help fix this, if it's considered as a bug, I only skimming the code, but I think it might an easy fix by @dvorka, then it's better for the author to fix.

**Comment by dvorka** [comment]
Fixed by b769fab.
