### ISSUE TITLE
Document bash vi bind mapping

### ISSUE THREAD

**Issue by grugnog** [dvorka/hstr#125]
It took me a few minutes to figure these out, and I suspect this may be useful to others:

```
bind '"\C-r": "\e^ihh \n"'
```

For the curious, \e is an escape, ^ to go to start of line, i to reenter insert mode and \n to execute the command. Perhaps there is a snazzier way of doing this, but it seems to work for me, so far.

**Comment by livibetter** [comment]
I have only used Emacs mode in Bash even I am a Vim user. The [configuration][] might just need a line or two, but `hh --show-configuration` would need more, here is what I've tried, first time using readline's `$if`:

[configuration]: https://github.com/dvorka/hstr/blob/master/CONFIGURATION.md#binding-hh-to-keyboard-shortcut

```bash
if [[ $- =~ .*i.* ]]; then bind <<EOF
$if mode=emacs
"\C-r": "\C-a hh \C-j"'
$else
"\C-r": "\e^ihh \n"
$endif
EOF
fi
```

Doesn't look clean, maybe `bind -v | grep 'set keymap emacs'`?

**Comment by dvorka** [comment]
Thank you @grugnog - I added the binding to MD documentation and man page. @livibetter I appreciate you suggestion, however, it would probably make default configuration too complicated - I added a hint to the default configuration produced by `hh -s` and enriched MD documentation.

**Comment by dvorka** [comment]
... @livibetter I changed (slightly ;) my mind - `hh` will produce default configuration as you suggested, but I will do that in time of running `hh -s` (i.e. in C), but in the produced script. I will be optimistic in a sense that user made Emacs vs. Vi choice and wont change it. It's better than nothing a slightly worse than you suggested. I created #126 enhancement.

**Comment by JacobDorman** [comment]
https://github.com/dvorka/hstr/blob/master/CONFIGURATION.md#bash-vi-keymap still has `bind '"\C-r": "\C-ahh \C-j"'` and the same is output with `--show-configuration`

This was the only place I could find the correct binding.

**Comment by asvc** [comment]
> `bind '"\C-r": "\e^ihh \n"'`

Perhaps worth adding the above to [README.md](https://github.com/dvorka/hstr/blob/master/README.md)?
