### ISSUE TITLE
/proc/$PID reading robustness

### ISSUE THREAD

**Issue by dvorka** [dvorka/hstr#127]
Make bash/zsh test robust - test it for cases when PID doesn't exist, proc/ not mounted, etc.

**Comment by ryanfb** [comment]
It would be nice to find a solution which also works on OS X, which doesn't have /proc. For me, this results in hstr not detecting that I'm using zsh, and as a result not using the zsh history item offset to ignore zsh history timestamps.

**Comment by dvorka** [comment]
Fixed by merging pull request.
