### ISSUE TITLE
Does this work with RHEL/CentOS?

### ISSUE THREAD

**Issue by druchoo** [dvorka/hstr#130]
Curious if this can be installed/build on RHEL 5/6 or other RPM based systems.

**Comment by dvorka** [comment]
There is no reason, why it wouldn't work, however, I didn't make any attempt to try it. Please give me some time so that I can install an eval RHEL version VM, try it (and possibly build RPM).

**Comment by squareatom** [comment]
Ok cool. FYI CentOS is the same as RHEL and free... I've updated subject.

**Comment by dvorka** [comment]
Resources:
* https://access.redhat.com/articles/142303
* https://fedoraproject.org/wiki/How_to_create_an_RPM_package
* http://www.g-loaded.eu/2006/04/05/how-to-build-rpm-packages-on-fedora/

**Comment by tbabej** [comment]
I'm on Fedora and it works just fine. Compiled from source.

**Comment by dvorka** [comment]
Good to know. Thanks!

**Comment by tbabej** [comment]
See https://copr.fedoraproject.org/coprs/tbabej/hstr/ and instructions in the Installation.md. I suggest this resolves the issue.

**Comment by dvorka** [comment]
Yes, it does - thank you @tbabej!
