### ISSUE TITLE
Release 1.17 for Fedora/.../CentOS

### ISSUE THREAD

**Issue by dvorka** [dvorka/hstr#151]
@tbabej please update repository files.

**Comment by tbabej** [comment]
Released for Fedora 21,22,rawhide, RHEL(CentOS/Scientific Linux) 5,6,7.

Build for Fedora 20 failed for some reason I have no time to investigate (it seems unrelated to hstr though), but given that F20 is EOL in less than a month, I let it go.

**Comment by dvorka** [comment]
@tbabej thank you a lot Tomas!
