### ISSUE TITLE
like it very much can't install it on my new Ubuntu 15.04

### ISSUE THREAD

**Issue by yonatanm** [dvorka/hstr#154]
will you release a version to http://ppa.launchpad.net/ supporting the new Ubuntu ?

**Comment by dvorka** [comment]
My apologies - I should do that much earlier: 32b/64b/ARM build is in the process...

**Comment by dvorka** [comment]
Distributions for Vivid are in PPA.

**Comment by yonatanm** [comment]
works like a charm. 10x dude.

**Comment by dvorka** [comment]
;)
