### ISSUE TITLE
Unnecessary newline when executeResult

### ISSUE THREAD

**Issue by livibetter** [dvorka/hstr#156]
For some time, there is *that* newline when you choose to execute the selected, e.g.

```bash
%  hh  # select and execute whatever
the_selected_command

% the_selected_command
[...]
```

*That* blank line really annoys me. I propose, if there is no particular reason for that newline:

```diff
diff --git a/src/hstr.c b/src/hstr.c
index 364416c..a99c939 100644
--- a/src/hstr.c
+++ b/src/hstr.c
@@ -1112,7 +1112,7 @@ void loop_to_select(Hstr *hstr)
         if(fixCommand) {
             fill_terminal_input("fc \"", FALSE);
         }
-        fill_terminal_input(result, TRUE);
+        fill_terminal_input(result, FALSE);
         if(fixCommand) {
             fill_terminal_input("\"", FALSE);
         }
```

It also removes the newline for `fixCommand`.

**Comment by livibetter** [comment]
@dvorka Can I offer an 1-liner PR for this? Or do you have more to add to this?

**Comment by dvorka** [comment]
@livibetter my apologies for the delay - I'm busy these days and I want to make thorough testing prior releasing this - I implemented that a long time ago and I'm not sure whether there is some purpose of new line (command execution vs. command to be edited) OR whether it's just L&F thing (when editing a command to have prompt on new line). Basically I want to test all options, find out whether it works, find out how it look likes and fix that. It might be that I will check what's the action and base on this I will keep/remove that new line.

Please stay tuned I'm giving this priority.
