### ISSUE TITLE
Create package for Debian Jessie > sid

### ISSUE THREAD

**Issue by harobed** [dvorka/hstr#162]
Create package for Debian Jessie

**Comment by calestyo** [comment]
hstr is in Debian sid now.

**Comment by dvorka** [comment]
@calestyo Thanks - this news made my day!

**Comment by calestyo** [comment]
Guess you can probably close the issue then :-)
Jessie's longterm support ends soonish... and if the original reporter would really still need it for jessie... he could probably just take the sid package and rebuild it there.
