### ISSUE TITLE
ssh.* pattern in regexp mode kills hh

### ISSUE THREAD

**Issue by garagatyi** [dvorka/hstr#163]
I tried hh by launching it, changing the mode with Ctrl-e and input ```ssh.*```. hh imediately exits.
Tried with 1.14 from repo for Ubuntu and with 1.17 from release archieve on github

**Comment by dvorka** [comment]
Not reproducible on 1.17 Ubuntu 14.04 64b PPA installation. If I understand that correctly, then the method is:

* use `ssh.*` pattern
* rotate matching mode with <kbd>Ctrl-e</kbd>
* rotate view with <kbd>Ctrl-/</kbd>

... `hh` should exit w/ SIGSEGV.

Do you get SIGSEGV or `hh` just exits? Which view (ranking/history/favorites) before rotating matching mode? What's your Ubuntu version? Do you use localized shell? Any other guess what might be specific to your installation? 

Thank you in advance!

**Comment by garagatyi** [comment]
I've missed views rotation in hh.
In history view everything is OK on both versions. hh exits in ranking view only.
Steps:
- enable ranking mode
- enable regexp mode
- put ssh.*

I've got exit code 134, lines from history, https://gist.github.com/garagatyi/655d317c9a2d4cc1279a

**Comment by garagatyi** [comment]
Also if I put ```ssh.*machine``` in the exact matching mode and then use Ctrl-e to enable regexp mode everything is ok. But if I erase symbols in query one by one hh fails when I get ```ssh.*m```

**Comment by phcyso** [comment]
I also get this on osx 10.11.1 with hh version "1.17" with zsh 5.0.8 (x86_64-apple-darwin15.0)
typing * by itself is fine, typing . by itself is fine but .* just crashes

    user@localhost$ .[1]    5668 abort      hh
    Type to filter, UP/DOWN move, DEL remove, TAB %

The lines in my .zshrc:

    export HISTFILE=~/.zsh_history  # ensure history file visibility
    export HH_CONFIG=hicolor,regexp,debug     # get more colors
    bindkey -s "\C-r" "\eqhh\n"     # bind hh to Ctrl-r (for Vi mode check doc)

I can duplicate it 100% when `.*` is the first thing typed. other things like s.* also fail but ssh.* sometimes works as expected.
I tried turning on debug in my zshrc but it doesn't output anything? is there a logfile it writes to?

**Comment by dvorka** [comment]
I attempted to reproduce this one (on Linux) again, however, with no success. I tend to think that there is an OS X specific problem - like a buggy `hh` dependency (regexp library?). Could you please use `strace` (or any similar tool):

```
strace hh 2> error.log
```

... and share `error.log` with me so that I can find out more details? Thank you in advance!

**Comment by phcyso** [comment]
Hey @dvorka I am not too familar with debugging this sort of thing so i hope these help.

I found that OSX generated a crash report, that is attached.
[hh_2015-11-13-210153_Kims-MacBook-Pro.crash.txt](https://github.com/dvorka/hstr/files/33826/hh_2015-11-13-210153_Kims-MacBook-Pro.crash.txt)

I also ran `sudo dtruss -afs -n hh` after opening hh in another terminal and captured the entering of the `.` and the `*` which gives the full stack backtraces.
[hh_dtruss.txt](https://github.com/dvorka/hstr/files/33833/hh_dtruss.txt)

Hope this helps.

**Comment by dvorka** [comment]
Thank you for sending trace files - dtruss seems to be useful. Looking into it, bud didn't find the problem yet. Please stay tuned.

**Comment by phcyso** [comment]
hey @dvorka I have been able to duplicate it in linux in a Ubuntu 14.04 vagrant vm.

Looks like it is something particular in my history file
Attached is a very censored copy of my .zsh_history file. 
All [a-zA-Z] chars replaced with f/F and [0-9] replaced with 1. symbols left as they are as i am guessing is something funny with them causing this. 
with this file i can duplicate the issue in mac and linux by switching to regexp mode and typing .* 
[thistory.txt](https://github.com/dvorka/hstr/files/42698/thistory.txt)

**Comment by dvorka** [comment]
@phcyso this is GREAT! I just reproduced the bug - fixing it should not be difficult. Thank you for your help!
