### ISSUE TITLE
Macport

### ISSUE THREAD

**Issue by dvorka** [dvorka/hstr#175]
Create proper Macport https://www.macports.org/ - any help from contributors will be appreciated!

Alternate screen can be disabled as follows http://superuser.com/questions/136162/how-can-i-still-see-the-man-text-after-i-quit-man/136205#136205 - I used the following method to reconfigure xterm:

```
infocmp | sed -e 's/[sr]mcup=[^,]*,//' > /tmp/noaltscreen-terminfo
tic -o ~/.terminfo/ /tmp/noaltscreen-terminfo
```

... and `hh` seems to work as usually.

**Comment by dvorka** [comment]
I changed code to leave content in page on exit (for non-alternative page):

https://github.com/dvorka/hstr/commit/3747f4edd774c7bc451de6be20a625ff8da1d227

**Comment by 1-61803** [comment]
[Done](https://trac.macports.org/ticket/53424).

**Comment by dvorka** [comment]
@1-61803 this is great! Thank you for the contribution - I really appreciate it!
