### ISSUE TITLE
Removing items in hstr does not delete the according timestamp

### ISSUE THREAD

**Issue by nkoester** [dvorka/hstr#176]
(Note: This is related to issue #124)

Let's assume we have a history with timestamps such as this:

<pre>
[...]
#1448445964
ls
#1448446124
cd workspace/
#1448446137
git clone https://github.com/dvorka/hstr.git
#1448446141
ls
#1448446150
cd hstr/src/
#1448446158
[...]
</pre>

When I delete the "ls" entries in this history, I get the following:

<pre>
[...]
#1448445964
#1448446124
cd workspace/
#1448446137
git clone https://github.com/dvorka/hstr.git
#1448446141
#1448446150
cd hstr/src/
#1448446158
[...]
</pre>

Which is not really nice. It does not break hstr but every delete will leave a dead timestamp line behind. I think this should not happen. The issue is the internal model of the history file simply [ignores the timestamp lines](https://github.com/dvorka/hstr/blob/master/src/hstr_history.c#L127):

```c
        [...]
        for(i=0; i<historyState->length; i++, rawOffset--) {
            if(!regexp_match(&regexp, historyList[i]->line)) {
                rawHistory[rawOffset]=0;
                rawTimestamps++;
                continue;
            }
        [...]
```

**Comment by dvorka** [comment]
Thank you for the bug report and suggestion - fix is on the way...

**Comment by dvorka** [comment]
Reproducible.

**Comment by nkoester** [comment]
This may bilindly delete comments in the history! This is actually a use case: entering a command with a leading "#" to store it as a comment for later execution in the history. 

Instead of [only checking for a leading #](https://github.com/dvorka/hstr/commit/008a4839ed0571a306d1dcaacd76054090c4ac88#diff-b4dbca1f7c6430fea5358a7b3a032d7cR233), applying [the regular expression](https://github.com/dvorka/hstr/blob/master/src/hstr_history.c#L117) is neccessary here!

**Comment by dvorka** [comment]
... lazy coder ;) You are obviously right - I will fix it.

**Comment by dvorka** [comment]
Just a thought - if timestamp/comment is preceding a command in history isn't it correct delete it regardless what it contains? What's purpose of keeping comments for commands that no longer exist?

**Comment by nkoester** [comment]
@dvorka First of all thanks for all your effort! I really value the work you do and don't want to sound demanding or anything. I really love hstr and only want to make it even more incredibly awesome as it is already =)

I use comments in my history not to comment on other lines in there but to remember a complex call without executing it. Often commands are only executable after certain other things have been done. For example:

I want to install something using python and setuptools. I type 
``` python
python setup.py install --prefix=/some/prefix/
```
But I realise this command will fail as the the prefix does not exist and I have not set my $PYTHONPATH. So I add the # in front - the command will be stored (but not executed) and I can do whatever is required to met the prerequisites. I then recall the stored command, remove the # and finally execute it.

Another good example are commands requiring plaintext passwords to be put it (not a good practice but well ...). I will execute those with a leading space to avoid storage in the history. But I still want to be able to recall the command, therefore I store a version without a password but with a leading # to be able to remember the command for later use:
``` bash
# some-command --user myuser --password CHANGEME
```

I hope you see what I mean.

**Comment by dvorka** [comment]
This makes perfect sense - thank you for the explanation! I just didn't want to leave garbage in the history file (as I did prior the fix). I appreciate your contribution!
