### ISSUE TITLE
Bash @ Win10 support

### ISSUE THREAD

**Issue by dvorka** [dvorka/hstr#186]
http://www.theverge.com/2016/3/30/11331014/microsoft-windows-linux-ubuntu-bash

**Comment by nickautomatic** [comment]
Has anyone had any luck with this? It seems to be very, very _nearly_ working in Bash on Ubuntu on Windows - the only issue is that when I select an item from the history it doesn't actually get executed / output to the command line. It feels like the kind of thing that might just need a config tweak or something to get it working...

**Comment by dvorka** [comment]
@nickautomatic thank you for giving it a try! I didn't have a Windows machine, but I bought one to my family members recently. If I'm able to [enable Ubuntu on Windows 10](http://www.omgubuntu.co.uk/2016/08/enable-bash-windows-10-anniversary-update) edition it's there, then I will fix that. BTW, code used to insert a command to console (to be executed) is based on `ioctl(0, TIOCSTI, &buf[i]);` - see [hstr_utils.c](https://github.com/dvorka/hstr/blob/master/src/hstr_utils.c). I will check whether it works on Windows, and if not a conditional compilation w/ different Windows specific working code might be a solution.

**Comment by nickautomatic** [comment]
@dvorka No problem! Thanks for the response.

Let me know if there's anything you'd like me to try. I have no experience of C, so probably can't help there, but am very happy to try things in Bash (change settings, etc) if there's anything more you'd like to know.

**Comment by dvorka** [comment]
@nickautomatic I just want to let you know that I installed the program and reproduced the problem. I'm in the process of writing test(s) in order to find a working solution/workaround.

**Comment by dvorka** [comment]
It might be that `TIOCSTI` is not supported, Windows `ioctl()` is used or Bash is not running in pseudo terminal... or something completely different - will see: https://github.com/Microsoft/BashOnWindows/issues/1863

**Comment by chappjc** [comment]
I've built hstr with the Creators Update and I can confirm it's not supported yet, as confirmed by @threalkenc in the [BashOnWindows](https://github.com/Microsoft/BashOnWindows/issues/1863#issuecomment-292745989) issue discussion.

Anyway, I'm eager to see a fix from MS and will be happy to test with their Ubuntu 16.04 environment.

**Comment by chappjc** [comment]
https://github.com/junegunn/fzf is able to add text to the terminal somehow.  It's a golang program, and I'm not sure what the runtime is doing.

**Comment by dvorka** [comment]
@chappjc thank you for pointing out `fzf` - I will definitely check that!

**Comment by dvorka** [comment]
See #164 which brought workaround for Cygwin where TIOCSTI is missing :-)

**Comment by jmiserez** [comment]
@dvorka The workaround from #164 could be adapted to not check for Cygwin using `#ifdef __CYGWIN__` but instead check for TIOCSTI with `#ifndef TIOCSTI`. TIOCSTI is not defined on platforms where it is not implemented.

**Comment by jmiserez** [comment]
PR with possible fix here: https://github.com/dvorka/hstr/issues/217

But it needs to be tested under Windows 10 (I don't have a Win 10 machine):

```
git clone https://github.com/jmiserez/hstr
cd hstr
git checkout windows-fix
cd dist
./1-dist.sh
cd ..
./configure
make
make install
hh --show-configuration >> ~/.bashrc
```
Then open a new Bash and test it.

**Comment by dvorka** [comment]
@jmiserez thank you for your experiments and summary - it helps! I tried a number of things to find a workaround, but I was not successful. I pretty sure that with #164 + my experiments results + your summary I will be able to deliver `hh` for WSL.

**Comment by dvorka** [comment]
Stupid and ugly hack ideal: `1-dist.sh` to check `/proc`  and create `/tmp/hh-on-wsl` file > `configure.ac` to check for `hh-on-wsl` existence using `AC_CHECK_FILE (file, [action-if-found], [action-if-not-found])` and define `AC_DEFINE([MICROSOFT_WSL], 1,[Define to enable WSL conditional compilation])`

**Comment by dvorka** [comment]
Unfortunately *variable-based* Cygwin workaround doesn't work for me on Win10:
```
         "\nfunction hstr_cygwin {"
         "\n  offset=${READLINE_POINT}"
         "\n  READLINE_POINT=0"
        "\n  { READLINE_LINE=$(</dev/tty hstr ${READLINE_LINE:0:offset} 2>&1 1>&$hstrout); } {hstrout}>&1"
         "\n  READLINE_POINT=${#READLINE_LINE}"
         "\n}"
         "\nif [[ $- =~ .*i.* ]]; then bind -x '\"\\C-r\": \"hstr_cygwin\"'; fi"
```
I will try temporary file version and debug the script command by command to find out where's the problem...

**Comment by jmiserez** [comment]
@dvorka Did you see that there is a typo in the temp-file based variant in the commit by @riedel? The last line should use READLINE_LINE not just READLINE.

I ran into that during testing, maybe check that?

**Comment by dvorka** [comment]
@jmiserez Actually both variants work for me now - I forgot to add conditional compiled code in `hstr_utils.c`. Thank you for all the suggestions :wink:

**Comment by IIIdefconIII** [comment]
> @dvorka Did you see that there is a typo in the temp-file based variant in the commit by @riedel? The last line should use READLINE_LINE not just READLINE.
> 
> I ran into that during testing, but it should only affect the cursor position, not put the output above the current prompt. Both variants are not Cygwin specific and should work on any Bash prompt. The tempfile based variant only uses basic redirection features, and should really work...

thanks for tagging me XD i moves over and put all my homeassistant in synology dockers instead and now use a rasp. pi for hyperion. Really preciate the tagging :)

**Comment by jmiserez** [comment]
> > @dvorka Did you see that there is a typo in the temp-file based variant in the commit by @riedel? The last line should use READLINE_LINE not just READLINE.
> > I ran into that during testing, but it should only affect the cursor position, not put the output above the current prompt. Both variants are not Cygwin specific and should work on any Bash prompt. The tempfile based variant only uses basic redirection features, and should really work...
> 
> thanks for tagging me XD i moves over and put all my homeassistant in synology dockers instead and now use a rasp. pi for hyperion. Really preciate the tagging :)

This is really off-topic. I appreciate the sentiment, but it's odd tracking people down like this on an different Github issue. In the future consider replying on the original Github issue instead (https://github.com/cantino/mcfly/issues/25) or just email me.
