### ISSUE TITLE
Build package for Xenial

### ISSUE THREAD

**Issue by wligtenberg** [dvorka/hstr#187]
Hi, I just upgraded to Xenial, and I assume in the near future a lot of people will run Ubuntu 16.04.
It would be nice if you could also support that release.

**Comment by dvorka** [comment]
Local build OK, however, LP build fails w/: https://launchpadlibrarian.net/256119508/buildlog_ubuntu-xenial-amd64.hh_1.20.1-0ubuntu1_BUILDING.txt.gz ... needs to be resolved.

**Comment by dvorka** [comment]
Distribution is ready: https://launchpad.net/~ultradvorka/+archive/ubuntu/ppa/+packages

**Comment by wligtenberg** [comment]
@dvorka Many thanks! Loving this small bit of software! (I think it should be the default. )

**Comment by dvorka** [comment]
My pleasure :wink:
