### ISSUE TITLE
Undocumented and/or not functional env variable HH_ENV_VAR_PROMPT

### ISSUE THREAD

**Issue by lee-pai-long** [dvorka/hstr#188]
I dvorka,

And first of all thank you for this great peace of software, it is very useful.

I wanted to change the default hh prompt to my `$PS1`, looking in the configuration documentation nothing  seems to describe how to it, but  searching a little bit in the code, the `hstr.c` module has a `print_prompt()` function that look for a `HH_ENV_VAR_PROMPT` environment variable to set the hh prompt to it if I understood correctly.

So I set this env var to `$PS1` in my `~/.bashrc` file:

```
export HH_ENV_VAR_PROMPT=$PS1
``` 

*Of course $PS1 is set before it in the file*

But it does not work, the prompt is still the default one.

Am I doing it wrong ? Is there something I didn't understand ?

**Comment by dvorka** [comment]
Hi @lee-pai-long! 

Please try `HH_PROMPT` as it's name of the environment variable (HH_ENV_VAR_PROMPT is name of C constant). However, copying $PS1 will not work for you as it contains Bash's DSL for prompt definition i.e. you have to somehow evaluate $PS1 to resulting prompt that can be in turn set to HH_ENV.

**Comment by lee-pai-long** [comment]
Thank you it works!

**Comment by dvorka** [comment]
:wink:
