### ISSUE TITLE
HH doesn't like sym / hard links for it's .hh_favourites file

### ISSUE THREAD

**Issue by sbrl** [dvorka/hstr#191]
I've just tried to move my `.hh_favourites` file to my bin folder in order to commit it to my git repo. In order to get hstr to recognise it, I symlinked it to `~/.hh_favourites`.

Oddly enough, my favourites were empty when I check to see if it worked. Thinking HH/HSTR must not get along with symlinks, I tried a hard link, which it didn't like either. Very odd indeed.

Is there a way that I can move my `.hh_favourites` so that I can commit it to my git repo?

**Comment by sbrl** [comment]
Nevermind, I'm an idiot. It turns out that I was using the `en-GB` (my native language) spelling of favorites, and not the `en-US` spelling.

**Comment by dvorka** [comment]
No problem - thank you for your interest in HH! :+1:
