### ISSUE TITLE
hh: invalid option -- 'P'

### ISSUE THREAD

**Issue by felikf** [dvorka/hstr#192]
Great tool btw. It saves me ton of typing. Thank you for sharing your effort!

when I type `mci -P` and press `Ctrl+R` then I get this:

```
hh: invalid option -- 'P'
Usage: hh [option] [arg1] [arg2]...
Shell history suggest box:

  --favorites              -f ... show favorites view
...
```

I am not sure if this is a feature or bug but I would expect to browse the history as usual, not the help to be printed out.

```
hh --version
hh version "1.19"
   build   "Nov 26 2015 21:18:22"
```

![image](https://cloud.githubusercontent.com/assets/13978154/18825982/61f01d54-83cb-11e6-84a0-9e730001d3b5.png)

**Comment by dvorka** [comment]
Thank you!

Ad bug: reproducible - command line builder to add options/parameters separator before parameters e.g.
```
hh -- mci -P
```

**Comment by dvorka** [comment]
Quickfix: you may easily fix this problem by changing the following line in `.bashrc` from:
```
bind '"\C-r": "\C-a hh \C-j"'    # bind hh to Ctrl-r                                         
```
to
```
bind '"\C-r": "\C-a hh -- \C-j"'    # bind hh to Ctrl-r                                         
```

**Comment by felikf** [comment]
Thank you.
