### ISSUE TITLE
Cannot delete items from .zsh_history

### ISSUE THREAD

**Issue by deadcyclo** [dvorka/hstr#200]
I've been using hstr since the very beginning, and I have never ever been able to get it to delete items from my history when using zsh. If I for example try to delete 'multitail' from my history, it says "History item 'multitail' deleted (0 occurrences)", and the entry doesn't get deleted. Any idea what is going on here?

**Comment by dvorka** [comment]
This seems to be a bug - let me reproduce it (I use Bash) and fix it. Thank you for letting me know!

**Comment by deadcyclo** [comment]
Great!

Let me know if you need any help testing or debuging.

**Comment by dvorka** [comment]
@deadcyclo I attempted to fix the bug - if the fix doesn't work, please send me example of line you are trying to delete from `.zsh_history`. I pushed fix to GitHub and I plan to release a new version (for Ubuntu via Launchpad) by the end of weekend.

**Comment by dvorka** [comment]
I just created Ubuntu release(s).

**Comment by deadcyclo** [comment]
@dvorka  Awesome. I can confirm it now works like a charm. Thank you :+1:

**Comment by dvorka** [comment]
Great!
