### ISSUE TITLE
Unexpected differences between 1.21 source tarballs

### ISSUE THREAD

**Issue by ryandesign** [dvorka/hstr#202]
There are unexpected differences between the [automatically-generated tarball][auto] and the [manually-generated tarball][manual] of 1.21. The expectation is that the [automatically-generated tarball][auto] contains the same files as the manually-generated tarball but that the latter has had the appropriate autoconf commands already run. This is not the case with your two tarballs.

Your [manually-generated tarball][manual] is from Oct 22, 2016 at 04:25 CST, while the [automatically-generated tarball][auto] is from 21 minutes later, at 04:46. There are significant differences, for example the [automatically-generated tarball][auto] contains a Changelog entry for 1.21, but the [manually-generated tarball][manual] does not. There are also differences in the installation and configuration instructions.

Did you perhaps inadvertently upload an earlier prerelease version of the manually-generated tarball? If so, could you release a new version 1.22 with the correct tarball?

[auto]: https://github.com/dvorka/hstr/archive/1.21.tar.gz
[manual]: https://github.com/dvorka/hstr/releases/download/1.21/hh-1.21-src.tar.gz

**Comment by dvorka** [comment]
I apologize for the inconsistencies. I just created [1.22 release](https://github.com/dvorka/hstr/releases/tag/1.22) and hope that tarballs are in sync. Thank you for issue creation and detailed description of the problem!

**Comment by dvorka** [comment]
Fixed.
