### ISSUE TITLE
Ctrl-R behaves incorrectly when prompt is at bottom

### ISSUE THREAD

**Issue by danielyli** [dvorka/hstr#207]
When `prompt-bottom` is enabled in `HH_CONFIG`, pressing `Ctrl-R` doesn't cycle the matches in reverse as it should; instead, it goes from the top of the reversed list.

**Comment by pknowles** [comment]
I'm hoping 8ba606e32fbfd4f75fa006d40a4191883c01b4e0 fixes this issue

**Comment by dvorka** [comment]
No longer reproducible on 1.28 and c9a3cfc594d985d5a32408e461b8fdecb83f75d2 - closing.
