### ISSUE TITLE
DEL doesn't remove item from shell history

### ISSUE THREAD

**Issue by 1-61803** [dvorka/hstr#208]

**Comment by dvorka** [comment]
Can you please provide me with version (`hh --version`), shell (Bash, Zsh) and other details (e.g. how delete entry looks like) so that I can reproduces the problem?

BTW, I did fixes related to history management prior 1.22 - if you have an older version, then please upgrade.

**Comment by 1-61803** [comment]
```
$ hh --version
hh version "1.22"
   build   "Feb  3 2017 22:22:10"
Desktop $ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin12.6.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Any entry cannot be deleted.

**Comment by dvorka** [comment]
Thank you for providing details! 

* Did you configured `hstr` in .bashrc? What history related configuration you have there?
* Can you please share which view do you use - it's black on white e.g. `- HISTORY - view:ranking ...` (ranking view)?
* Do you see a prompt after pressing <kbd>DEL</kbd>  `Do you want to delete all occurrences of 'tig'? y/n`?
* How many occurrences of deleted entry/entries is there (there might trailing space and entries look the same)?
* How do you exit `hstr` - <kbd>Esc</kbd>, <kbd>Ctrl</kbd>-<kbd>g</kbd>, ...?
* By "does nothing" you mean that - you run `hstr`again and entry is there OR you check `.bash_history` OR you run `history` commands?
* Do you get any errors or `hstr` simply does nothing?

Apologies for many questions, but I need to reproduce the problem and isolate where it is. Thanks again for your help!

**Comment by 1-61803** [comment]
* This is my configuration that I source from a separate file in `/etc/profile`.
```
# hstr (default options modified)
export HH_CONFIG=hicolor,keywords,rawhistory  #+get more colors
shopt -s histappend                           # append new history items to .bash_history
export HISTCONTROL=ignorespace                # leading space hides commands from history
export HISTFILESIZE=10000                     # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}               # increase history size (default is 500)
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"   # mem/file sync
# if this is interactive shell, then bind hh to Ctrl-r (for Vi mode check doc)
if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hh -- \C-j"'; fi
export HH_PROMPT="$ "
```

* My view is `history` — an aside, as said in #203 I cannot change it with `Ctrl-7`.

* After pressing `DEL` I don't see any prompt.

* One unique occurrence cannot be deleted.

* Exit with both 2x`ESC` and `Ctrl-g` work (caveat #203).

* Running `hh` again or `history` shows the entry there.

* No errors, `hstr` does nothing after pressing `DEL`.

**Comment by 1-61803** [comment]
I noticed you labeled it `os x`, is it so only?

**Comment by 1-61803** [comment]
I had `DEL` mapped to `Ctrl-d`. My bad.

**Comment by dvorka** [comment]
It's great the you determined the cause of the problem. Thank you for using `hh` and letting me know!

**Comment by thinker3** [comment]
fn + delete
