### ISSUE TITLE
Enhancement: Configurable keys via config file

### ISSUE THREAD

**Issue by danielyli** [dvorka/hstr#209]
Muscle memory instinctively tells me `Ctrl-J` and `Ctrl-K` are for scrolling up and down.  It would be nice to be able to set these keys via a configuration file.

**Comment by dvorka** [comment]
@danielyli I really appreciate your interest in `hstr`, however, I don't plant to extend it's code with such functionality - I want to keep it relatively small and simple. Please feel free to customize the source code and/or contribute this functionality. Thanks!
