### ISSUE TITLE
How to set default mode?

### ISSUE THREAD

**Issue by antonmedv** [dvorka/hstr#210]
How to open by C-r in mode by default:
```
view:history (C-7) - match:keywords (C-e) - case:insensitive
```

**Comment by dvorka** [comment]
Set `HH_CONFIG` variable to:
```
export HH_CONFIG=rawhistory,keywords,hicolor
```
e.g. in `.bashrc`. If you did `hstr` installation using `hh -s >> ~/.bashrc` just edit existing values.

**Comment by antonmedv** [comment]
Thanks! Docs will be cool.

**Comment by dvorka** [comment]
Your are welcome! Ad docs - please try `man hh`.
