### ISSUE TITLE
Debian: no hstr distro for Wheezy and Jessie

### ISSUE THREAD

**Issue by sbrl** [dvorka/hstr#214]
The ppa for debian wheezy can't be found (and there isn't one for debian jessie either :confused:). Here are the sources I'm using:

```
deb http://www.clfh.de/debian wheezy main
deb-src http://www.clfh.de/debian wheezy main
```

**Comment by jam1e** [comment]
Nothing for Stretch either

**Comment by dvorka** [comment]
This PPA was contributed by a HSTR user in the past. It's probably time for **me** to set up PPA for Debian on mindforger.com: https://wiki.debian.org/DebianRepository/SetupWithReprepro

Please stay tuned.

**Comment by dvorka** [comment]
I created new PPA for Debian: http://www.mindforger.com/debian/

**Comment by sbrl** [comment]
Any chance for `armhf` builds in that ppa too?

**Comment by sbrl** [comment]
Hrm. Looks like that article you've linked pretty much covers the process. If you're after a GUI, have you seen _[Virtual Machine Manager](https://virt-manager.org/)_?
