### ISSUE TITLE
Clear prompt line on cancel

### ISSUE THREAD

**Issue by pknowles** [dvorka/hstr#218]
If I cancel with ctrl-c or ctrl-g I'll often end up with the characters from the history list covering the prompt line. Using the following bind command fixes ctrl-c by sending ^K on failure. It would be nice if this was built-in.

    bind '"\C-r": "\C-a hh -- || echo -ne \\\\013\C-j"'

It might be useful to have ctrl-g return a failure code too.

**Comment by dvorka** [comment]
Make sense! I will incorporate it once I process and test my queue of merge requests. Thanks!

**Comment by pknowles** [comment]
I must apologise. I had `TERM` set incorrectly which was causing the alternative screen ncurses uses to fail.
