### ISSUE TITLE
Pack as snap

### ISSUE THREAD

**Issue by techtonik** [dvorka/hstr#225]
It could be easier to install `hh` with `snap` - https://snapcraft.io/

**Comment by brennv** [comment]
I attempted some snap builds using this config:
https://github.com/brennv/hstr/blob/master/snap/snapcraft.yaml

But they are not working yet:
https://build.snapcraft.io/user/brennv/hstr/139604

We may need to revise configure and make, without needing to build first in dist/... still looking

**Comment by dvorka** [comment]
I just added contributed script by @fszymanski to the branch 1.27 bff735a79b47f362e9166cb0a46325e71d1a5a07.
