### ISSUE TITLE
Problem replacing ctrl-r with hh with bash

### ISSUE THREAD

**Issue by johnmccabe** [dvorka/hstr#227]
Hi,
I'm trying to replace the built-in ctrl-r search with hh in bash on OSX but I get the following error using the bash vi keymap example.

This is the entry in my bash_profile:
```
if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-ahh -- \C-j"' ; fi
```

```
$ ^Ahh --
-bash: hh: command not found
```

hh is on the path and I can get it running by removing the `\C-a` but that leaves the `hh` command in the history.

I'm using iterm2 with the following
```
SHELL = /bin/bash
TERM = xterm-256color
keymap = vi-insert
editing-mode = vi
```

Any suggestions as to what I've borked here?
Thanks.

**Comment by johnmccabe** [comment]
I've tried installing on a fresh linux instance and the default bash config works without any issue.

Will close this as the problem appears to be on my side.

Cool tool, thanks !!!

**Comment by gertcuykens** [comment]
I have the same problem on OSX, did you find what it was?

**Comment by gertcuykens** [comment]
Found it need to be bind '"\C-r": "hh -- \C-j"'

**Comment by dvorka** [comment]
@gertcuykens Thanks!
