### ISSUE TITLE
Was 1.22 retagged?

### ISSUE THREAD

**Issue by ilovezfs** [dvorka/hstr#231]
Currently the SHA-256 checksum for https://github.com/dvorka/hstr/archive/1.22.tar.gz is 384fee04e4c80a1964dcf443131c1da4a20dd474fb48132a51d3de0a946ba996.

Originally it was c4995e7041dc66e2118f83bd4c6c7f4cff5b4c493ca28bd7e4aef76edeff71ba. See https://github.com/Homebrew/homebrew-core/pull/9590.

Was 1.22 retagged at some point?

**Comment by ilovezfs** [comment]
@dvorka any idea what happened?

**Comment by ilovezfs** [comment]
@dvorka gentle ping on this. Currently users cannot install `hh` in Homebrew due to this issue. We can't update the checksum until we understand the circumstances here.

**Comment by dvorka** [comment]
My apologies for delayed response. There were inconsistencies related to tags and releases, but I'm not exactly sure whether I changed the tag (don't see anything suspicious in log and distro).

Perhaps I can release 1.23 - would this solve the problem?

**Comment by ilovezfs** [comment]
>Perhaps I can release 1.23 - would this solve the problem?

yes that would be perfect :)

**Comment by dvorka** [comment]
I just released https://github.com/dvorka/hstr/releases/tag/1.23

Please let me know whether it helped. **Thank you** for letting me know and Homebrew distribution support!

**Comment by ilovezfs** [comment]
Thank @dvorka (and you're welcome)! Voilà: https://github.com/Homebrew/homebrew-core/pull/18770
