### ISSUE TITLE
Cannot install HSTR on Ubuntu 17.04

### ISSUE THREAD

**Issue by FlorentDancy** [dvorka/hstr#232]
Hi,

I just tried to install HSTR on my Ubuntu 17.04 by executing, as asked [here](https://github.com/dvorka/hstr/blob/master/INSTALLATION.md#ubuntu):

`sudo add-apt-repository ppa:ultradvorka/ppa && sudo apt-get update && sudo apt-get install hh && hh --show-configuration >> ~/.bashrc`

Unfortunately, it doesn't work, CF error log [over here](https://pastebin.com/cU7DjRSE).

If there's anything I can do to help on the resolution of this problem, tell me!

Flo

--------------------------------

This is my setup:

```bash
$ uname -r
4.10.0-35-generic

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

**Comment by dvorka** [comment]
It's there https://launchpad.net/~ultradvorka/+archive/ubuntu/ppa/+packages

Enjoy!

**Comment by FlorentDancy** [comment]
@dvorka thank you so much! :)
