### ISSUE TITLE
sha256sums does not match

### ISSUE THREAD

**Issue by smartshogu** [dvorka/hstr#234]
Hello dvorka,

when building the package i get an error from the validation check:

> ==> Validating source files with sha256sums...
>    hstr-1.23.tar.gz ... FAILED
> ==> ERROR: One or more files did not pass the validity check!

**Comment by dvorka** [comment]
Most probably related to bug #237.

**Comment by dvorka** [comment]
Hopefully fixed by fix of #237 - please let me know if the problem persists.
