### ISSUE TITLE
Reversed view (cursor at the bottom)

### ISSUE THREAD

**Issue by max-lobur** [dvorka/hstr#241]
When you work in a shell your active line is always at the bottom, but history search starts from the top, this is inconvenient.

If you show history in a reversed way (latest at the bottom) and draw a selector at the bottom of the screen - it will look much more natural and won't force your eyes to jump.

**Comment by dvorka** [comment]
When you use HSTR w/ bottom prompt (just add `prompt-bottom` to HH_CONFIG environment variable - e.g. `export HH_CONFIG=hicolor,prompt-bottom`, check man for more details) your latest history items should be at the bottom when using bottom prompt (I use version 1.22) i.e. history/favorites/... are reversed. Are you sure that your latest entries are at the top of the page?

**Comment by max-lobur** [comment]
Well, prompt-bottom works for me.
For the history order - I can barely understand it, it doesn't match the order of items I get with Ctrl-R in zsh (which I like more for now). Probably because I have shared history enabled in zsh, and because it is flushed to history file with a delay. 
Anyways, thanks for the prompt-bottom, this is what I needed!

**Comment by max-lobur** [comment]
Ah I got it. I also needed `rawhistory` to make it work
