### ISSUE TITLE
Ctrl-7 doesn't switch ordering on MacOS

### ISSUE THREAD

**Issue by megamattron** [dvorka/hstr#258]
I prefer seeing recent commands (side note: the # of occurence ranking metric just seems to prioritize long lines), but I can't seem to switch rankings. I'm on v1.24.

Thanks!

**Comment by dvorka** [comment]
As a workaround please change your configuration (most probably located in `~/.bashrc`) 
to something like `HH_CONFIG=rawhistory,hicolor` (`rawhistory` changes the view). You can also export the variable to use it/test it.

Check `man hh` for more details and other options.

**Comment by megamattron** [comment]
Cool thanks, I've made that change since that's the view I want anyway.
