### ISSUE TITLE
Fuzzy history matching

### ISSUE THREAD

**Issue by sxe** [dvorka/hstr#260]
Hi, 
I love hh, it has changed they way I work with my shell!

That being said, I would love to have fuzzy history matching. More often than not I am searching the history for calls like this: 

`$ program --param1 path --param2`

I would love to search like this:

`search: prog --param2 `

and get the correct result. 

Thx and keep up the great work.

**Comment by dvorka** [comment]
Did you try keyword style search? If not, add to your environment configuration variable `keywords` setting:
```
export HH_CONFIG=hicolor,keywords
```
First try it in current shell, they you may want to add it e.g. to `.bashrc`. IMO this settings changes search in the way you described - I use `hh` with this configuration myself. For more details please refer to `man hh`.

Thank you for kind words - I really appreciate it! :+1:

**Comment by sxe** [comment]
Wow, yeah that's exactly what I was looking for. I checked the man page but for some reason didn't find it. Maybe I was too focused on the term "fuzzy". :) Thx a lot!

**Comment by dvorka** [comment]
:smile:

**Comment by nkakouros** [comment]
Would it be possible to have truly fuzzy search? Eg, using the examplle above, typing `propar2` would still match that command.
