### ISSUE TITLE
Can we have a hot key to just leave the selected command on the command line without launching it?

### ISSUE THREAD

**Issue by doubledodge** [dvorka/hstr#263]
Possible enhancement? Having selected the most appropriate command from history I generally need to edit it slightly before launching it but I don't seem to be able to stop my selected command from immediately executing if I exit hh with ctrl-g.  Would it be possible to just paste the command from history to the command line on exiting hh with a new ctrl key combination? Just pasting a selected command to the command line from hh would allow me to do my edits using the normal bash command line editing keys.

**Comment by dvorka** [comment]
Please try <kbd>TAB</kbd> or <kbd>&rarr;</kbd> when on a selected history entry to copy it to the command line **without** execution.

Check `man hh` for more details and shortcuts.
