### ISSUE TITLE
Feature request: Emacs Helm like search: Treat space as .*

### ISSUE THREAD

**Issue by AshKash** [dvorka/hstr#267]
Emacs Helm or Ivy lets you do fuzzy text matching by separating partial tokens with a space and this is very quick to type and very useful. It should be easy to roughly mimc the behavior -- can we treat space as .* and map "\ " to regular space when in match:regexp mode?

**Comment by dvorka** [comment]
Did you try keyword style search? If not, add to your environment configuration variable keywords setting:
```
export HH_CONFIG=hicolor,keywords
```
... and try it in current shell, then you may want to add it e.g. to .bashrc. 

This setting is very similar to what you are looking for - write space separated (framents of) words and `hh` will match all of them (fragments can be in any order). In other words, it is less strict (escaped space is not supported),  but easier to write (you don't have to write regexps).

If you thing that **fuzzy** search (regexps with spaces treated as `.*` and ability to require escaped space are worth to implement/there are important use cases just let me know (in this thread) and I will add it to my plans.

**Comment by AshKash** [comment]
👍 awesome, works great
