### ISSUE TITLE
Order of favorite commands

### ISSUE THREAD

**Issue by 1-61803** [dvorka/hstr#276]
When I select a command from favorites with `hh -f` it changes the order the list of favorites is in, making the selected command the first one next time I recall the favorites. Ideally, the favorites list could be made optionally static and provided with comments and sections.

**Comment by dvorka** [comment]
I will make a `HH_CONFIG` option which will disable favorites reordering.

**Comment by 1-61803** [comment]
That's great, thanks!

Is it possible add comments to`~/.hh_favorites`?

**Comment by 1-61803** [comment]
That's great, thanks!

Is it possible to add comments to `~/.hh_favorites`?

**Comment by dvorka** [comment]
You can add comment at the end of any command e.g.:
```bash
 printf "\e[?2004l" # fix broken copy/past in Terminator terminal
...
```

**Comment by 1-61803** [comment]
I haven't tried it yet, but also meant line comments, not just inline. And line spaces, for that matter. My favorites are getting crowded and I'd like to reorder them a bit.

**Comment by dvorka** [comment]
I just added configuration option (`static-favs`) that disables favorites reordering (new favorites are appended). It will be released with the next version.

Ad comments:
* I personally like inline comments - you can use them for tagging commands like:
```
COMMAND # TAG1 TAG2 TAG3
...
printf "\e[?2004l" # fix broken copy/paste in terminal #TERM
```
* You can reorder commands, add empty lines and lines with comments to favorites with the new option. However, favorites are filtered on line granularity. Therefore line with comments may appear among matching commands.

**Comment by 1-61803** [comment]
Right now on 1.24 (20180221) in macOS I see

    view:history (C-7)

but `C-7` doesn't work, `C--` does and it's fine by me.

Then why don't you just change what's *showing* to

    view:history (C--)

**Comment by 1-61803** [comment]
Thanks for adding `static-favs`. I'll see if I can give it a try.

Maybe you could add an option to ignore line comments, ie, lines beginning with `#`, or to show the line following the matching line comment for context.

    # matching line comment in search
    echo 'this line shows for context'

**Comment by dvorka** [comment]
Check #302 :wink:
