### ISSUE TITLE
building fails in arch

### ISSUE THREAD

**Issue by smartshogu** [dvorka/hstr#297]
Hello Martin Dvorak,

when building Version 1.27.r4 in arch i get this message:

> In file included from hstr.c:21:
> include/hstr.h:29:12: fatal error: ncursesw/curses.h: No such file or directory
>    #include <ncursesw/curses.h>
>             ^~~~~~~~~~~~~~~~~~~
> compilation terminated.

Would be nice to have it in AUR again. Thanks.

**Comment by kinoegit** [comment]
hstr-git 1.27.r4.g5894e93-1
building error here: /tmp/yaourt-tmp-kinoe/aur-hstr-git/./PKGBUILD: line 19: cd: hstr/dist: No such file or directory

**Comment by smartshogu** [comment]
Hello Martin Dvorak,

this commit:
https://github.com/dvorka/hstr/commit/8ce60a877d2c989e394eb4bc525e3847256ae36d#diff-530bed8bddbf92cdf0187325e3fa686f

changes the file hstr.h, wich causes the error when building the package.

After editing line 29 to `#include <curses.h>` the package is build again.
If the change is possible for hstr, it would be nice to have it in the master branch.

Thank you.

**Comment by dvorka** [comment]
@kinoegit Please use https://github.com/dvorka/hstr/blob/master/PKGBUILD directories changed (note e.g. `... tarball-automake.sh ...`)

@smartshogu Thank you for making workaround. **RESOLUTION**: I need to fix `sed` in PKGBUILD - includes has been moved to the different header file(s).

@smartshogu @kinoegit I will fix PKGBUILD in Git (you will see status in here), then I will notify AUR maintainers https://aur.archlinux.org/packages/?O=0&SeB=nd&K=hstr&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by dvorka** [comment]
PKGBUILD @ GitHub fixed.

**Comment by papavlos** [comment]
@dvorka 
Please be so kind and correct exactly the same issue in file `hstr_curses.h` in line 27.

I am also Arch user, but have installed hstr following the "Build on any Linux distro" procedure, not from AUR. And I had to correct manually both header files: `hstr.h` in line 29 and `hstr_curses.h` in line 27. After that `make` has completed successfully.

And many thanks for this tool !!!

**Comment by smartshogu** [comment]
Works fine. AUR is also updated. Thanks for your efforts.

**Comment by dvorka** [comment]
@smartshogu Thank you for maintaining AUR for HSTR! :wink:
