### ISSUE TITLE
Add an option to ignore line comments in .hstr_favorites

### ISSUE THREAD

**Issue by dvorka** [dvorka/hstr#302]
Add an option to ignore line comments, ie, lines beginning with #, or to show the line following the matching line comment for context.

```
# matching line comment in search
echo 'this line shows for context'
```

See also #276.

**Comment by 1-61803** [comment]
Great! Looking forward to it…

**Comment by dvorka** [comment]
Use `HH_CONFIG=skip-favs-comments` to skip comments. This feature will be released with the new version.
