### ISSUE TITLE
Compilation failed on Manjaro 17.1.12

### ISSUE THREAD

**Issue by lejurassien** [dvorka/hstr#315]
[fred-manjaro hstr]# ./configure && make && make install
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/sbin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for pkg-config... pkg-config
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/sbin/grep
checking for egrep... /usr/sbin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for killwchar in -lncursesw... yes
checking for cos in -lm... yes
checking for using_history in -lreadline... yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking readline/history.h usability... yes
checking readline/history.h presence... yes
checking for readline/history.h... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking for stdbool.h that conforms to C99... (cached) yes
checking for _Bool... yes
checking for size_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for memset... yes
checking for strdup... yes
checking for strstr... yes
checking for /tmp/hstr-ms-wsl... no
checking for pkg-config... /usr/sbin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for BASH_COMPLETION... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: executing depfiles commands
Making all in src
make[1] : on entre dans le répertoire « /home/fred/Téléchargements/hstr/src »
gcc -DPACKAGE_NAME=\"hstr\" -DPACKAGE_TARNAME=\"hstr\" -DPACKAGE_VERSION=\"2.0.0\" -DPACKAGE_STRING=\"hstr\ 2.0.0\" -DPACKAGE_BUGREPORT=\"martin.dvorak@mindforger.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"hstr\" -DVERSION=\"2.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBNCURSESW=1 -DHAVE_LIBM=1 -DHAVE_LIBREADLINE=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MEMSET=1 -DHAVE_STRDUP=1 -DHAVE_STRSTR=1 -I.    --pedantic -Wall -std=c99 -O2 -g -O2 -MT hashset.o -MD -MP -MF .deps/hashset.Tpo -c -o hashset.o hashset.c
mv -f .deps/hashset.Tpo .deps/hashset.Po
gcc -DPACKAGE_NAME=\"hstr\" -DPACKAGE_TARNAME=\"hstr\" -DPACKAGE_VERSION=\"2.0.0\" -DPACKAGE_STRING=\"hstr\ 2.0.0\" -DPACKAGE_BUGREPORT=\"martin.dvorak@mindforger.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"hstr\" -DVERSION=\"2.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBNCURSESW=1 -DHAVE_LIBM=1 -DHAVE_LIBREADLINE=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MEMSET=1 -DHAVE_STRDUP=1 -DHAVE_STRSTR=1 -I.    --pedantic -Wall -std=c99 -O2 -g -O2 -MT hstr_curses.o -MD -MP -MF .deps/hstr_curses.Tpo -c -o hstr_curses.o hstr_curses.c
In file included from hstr_curses.c:20:
include/hstr_curses.h:27:10: erreur fatale: ncursesw/curses.h : Aucun fichier ou dossier de ce type
 #include <ncursesw/curses.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminée.
make[1]: *** [Makefile:402: hstr_curses.o] Error 1
make[1] : on quitte le répertoire « /home/fred/Téléchargements/hstr/src »
make: *** [Makefile:408: all-recursive] Error 1

Is something to do ?? thanks

**Comment by smartshogu** [comment]
Hello lejurassien, you can use the aur package if you want:
https://aur.archlinux.org/packages/hstr-git/

**Comment by dvorka** [comment]
@lejurassien can you please send exact distribution version - I would like to create virtual machine and attempt to reproduce your problem.

@smartshogu This is great response! Do you think that I can add Manjaro to the list of supported distributions and use http://dvorka.github.io/hstr/INSTALLATION.html#arch-linux ?

**Comment by lejurassien** [comment]
@ Dvorka 
Thanks, that's what I did.
And it's manjaro deepin desktop 17.1.12 
@smartshogu  Thank's for your work !!!

**Comment by smartshogu** [comment]
Hello dvorka, feel free to add manjaro to the list.
I discovered your program a while ago and adopted the AUR-package after it became an orphan. 
And i can say - I like maintaining it so far.

Here is my amendment to your INSTALLATION.md

> To install HSTR on Arch or Manjaro Linux download latest distribution from GitHub releases.
> 
> Use PKGBUILD in the root of the distribution to build package using makepkg.
> 

To install hstr from the [Arch User Repository (AUR)](https://aur.archlinux.org/packages/hstr-git/) run `yaourt -S hstr-git` in command line.

>
> Configure HSTR and check its man page.

**Comment by dvorka** [comment]
@smartshogu I just updated installation notes. Thank you for being AUR-package maintainer - I really appreciate it! :wink:
