### ISSUE TITLE
hstr reads bash history in zsh

### ISSUE THREAD

**Issue by deathtrip** [dvorka/hstr#317]
Using Arch Linux hstr 1.24, on zsh i get bash history selection instead of zsh.
HISTFILE is present in .zshrc.
Could be related to #272 and #166

**Comment by dvorka** [comment]
@deathtrip thank you for the issue submission! I plan to devote the next release to `zsh` and fix all the bugs. Stay tuned please.

**Comment by dvorka** [comment]
Reproducible on 18c996852cdde4ef53e7bf843c244c86c3e0bdb2

**Comment by dvorka** [comment]
Fix will be released w/ HSTR 2.1
