### ISSUE TITLE
Regex duplicate results selection.

### ISSUE THREAD

**Issue by arbach** [dvorka/hstr#335]
Not sure if this is by design, **regex** mode will return multiple  results for the same search  vs. one results when using **keywords**

![jan01mde4ym](https://user-images.githubusercontent.com/6321847/50612461-bf162800-0e9f-11e9-89f5-f8fef1b2065e.png)

would be nice to have only one for each match.

**Comment by dvorka** [comment]
@arbach please change view from `history` to `ranking`. History view is normal Bash history view with duplicates, while `ranking` doesn't contain duplicate and orders commands by HSTR metrics (frequency, time, length, ...).
