### ISSUE TITLE
How to delete history in macOS?

### ISSUE THREAD

**Issue by foray1010** [dvorka/hstr#347]
the `delete` button by default is `backspace` button in mac keyboard
the delete button only work as delete by pressing `command + delete`, but seems it is not supported by hstr 2.0.0, there is no response when I'm pressing that combination

I am using macos 10.14.4, default terminal.app along with `zsh 5.7.1`

**Comment by foray1010** [comment]
seems it is just default terminal.app's problem, switched to Alacritty with custom config fixed the issue
```yaml
- { key: Back,     mods: Command,   chars: "\x1b[3~"                  }
```

**Comment by loikein** [comment]
Hi, I actually cannot delete in iTerm2. Is there any way to change the keybindings?

**Comment by Frank5000** [comment]
`shift+fn+delete` for me
