### ISSUE TITLE
Instructions for Ubuntu don't work on 19.04?

### ISSUE THREAD

**Issue by MostHated** [dvorka/hstr#356]
Hey there,
    I attempted to install by adding the PPA and updating, but it came back with:

```
Err:33 http://ppa.launchpad.net/ultradvorka/ppa/ubuntu disco Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/ultradvorka/ppa/ubuntu disco Release' does not have a Release file.
```

Thanks,
-MH

**Comment by pauldotknopf** [comment]
I took would like this as well.

Thanks!

**Comment by dvorka** [comment]
Sure - let me prepare new builds. I tried to build HSTR on new Ubuntu releases, but there were changes in libreadline versions and it seems that certain HSTR functions will have to be reimplemented. I'm going to prepare VMs and share progress in here.

**Comment by dvorka** [comment]
WIP:
```
dpkg-buildpackage: info: source changed by Martin Dvorak (Dvorka) <martin.dvorak@mindforger.com>
 dpkg-source --before-build hstr-2.0.8
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 8.0.0) libreadline-dev libncursesw5-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -S failed
bzr: ERROR: The build failed.
```

**Comment by dvorka** [comment]
I finally succeeded in building HSTR for [Ubuntu 19.04 Disco Dingo](https://wiki.ubuntu.com/Releases) on Launchpad:

* https://launchpad.net/~ultradvorka/+archive/ubuntu/ppa/+sourcepub/10785989/+listing-archive-extra

@MostHated @pauldotknopf please give it a try.
