### ISSUE TITLE
Ubuntu 19.04: build fails

### ISSUE THREAD

**Issue by anne17** [dvorka/hstr#359]
I'm getting the following error when trying to build from source on Ubuntu 19.04:
```./configure:` line 5036: syntax error near unexpected token `BASH_COMPLETION,'
./configure: line 5036: `    PKG_CHECK_MODULES(BASH_COMPLETION, bash-completion >= 2.0,'```

**Comment by zvezdochiot** [comment]
https://github.com/dvorka/hstr/blob/930b054848f84810a7373342726a3af645fd5d30/configure.ac#L122-L139

**Comment by dvorka** [comment]
@anne17 please install `bash-completion`:

* https://www.cyberciti.biz/faq/add-bash-auto-completion-in-ubuntu-linux/
