### ISSUE TITLE
Ubuntu 19.10: not found

### ISSUE THREAD

**Issue by messelmanibrahim** [dvorka/hstr#362]
The repository 'http://ppa.launchpad.net/ultradvorka/ppa/ubuntu eoan Release' does not have a Release file.

**Comment by sourcecase** [comment]
I solved it by following the build  instructions https://github.com/dvorka/hstr/blob/master/INSTALLATION.md#build-on-ubuntu and adding a symlink to "hstr/src/hstr".

But yes a PPA for Ubuntu "eoan" would be nice.
