### ISSUE TITLE
Different zsh history file on Manjaro / Arch

### ISSUE THREAD

**Issue by smartshogu** [dvorka/hstr#367]
Hello Dvorak,

with version 2.1 i get an error using zsh on Manjaro / Arch

> Unable to read history file from '/home/_user_/.zsh_history'

Instead .zsh_history the history file is called .zhistory

As a workaround a placed a simlink to .zsh_history but perhaps you can find a better solution.

.
Thanks so far and have a good day.

**Comment by dvorka** [comment]
@smartshogu can you please check whether you have `HISTFILE` environment variable set please?
```
echo $HISTFILE
```
I twould help me to make code more robust. Thanks!

**Comment by dvorka** [comment]
Resolution: implement a method which will sniff for history file in the same way `zsh` does: https://unix.stackexchange.com/questions/172057/why-does-oh-my-zsh-pick-zhistory-instead-of-zsh-history-for-the-value-of-histf

**Comment by smartshogu** [comment]
Hello dvorka.
My output of echo $HISTFILE is /home/user/.zhistory.
I tried the new version from dev 2.2 and works again. Nice job ;)

**Comment by dvorka** [comment]
@smartshogu thank you for verifying that enhancement works - I really appreciate it! I will release it w/ the next HSTR version!
