### ISSUE TITLE
Alternatives?

### ISSUE THREAD

**Issue by zvezdochiot** [dvorka/hstr#369]
Add alternative utilities to the documentation:

* fzy (https://github.com/jhawthorn/fzy)
```sh
$(history | cut -c 8- | fzy)
$(cat ~/.bash_history | fzy)
$(cat ~/.hstr_favorites | fzy)
```

**Comment by dvorka** [comment]
Nice! Inspiration as well, however, I think that there are zillions of _alternative to_ web sites/articles/forum posts around the web. Don't think that it would be useful to have in HSTR documentation...
