### ISSUE TITLE
Help dissapears when configured for bottom location

### ISSUE THREAD

**Issue by dvorka** [dvorka/hstr#374]
Repro:
* Configure HSTR to show help at the bottom using `help-on-opposite-side`.
* Start HSTR
* Type a character, page will refresh and menu dissapears.

Hints:
* `export HSTR_CONFIG=hicolor,help-on-opposite-side,prompt-bottom` works as expected.
* Reproducible on `export HSTR_CONFIG=hicolor,help-on-opposite-side`.

Check https://github.com/dvorka/hstr/pull/371 for changes and determine whether it's a new bug or it was introduced w/ new changes.

CC @bibermann

**Comment by bibermann** [comment]
Oh, never checked typing with this config, only selecting items...

In my PR I added [this TODO](https://github.com/dvorka/hstr/blob/dev/2.2.0/src/hstr.c#L1077) and this indeed is related.

If I call the following two function not only if `hstr->promptBottom` but also if `helpOnOppositeSide`, then the labels reappear:
```c
        print_help_label();
        print_history_label();
```

But I do not understand this part of the code well enough to give the real conditions for the rerendering. Also note that my comment "TODO: Why is this printed conditionally? Make a comment or fix!" appears on two places in the code; both may need a fix.

**Comment by dvorka** [comment]
There are many combinations now. And yes - I checked your comments. I will need to review/debug the code, because I wrote it a long time and several PRs ago.

Anyway thank you for your contribution! I really like it and I plan to start using HSTR with hidden help lines on my personal notebook. Good job!

**Comment by bibermann** [comment]
I made a PR that tries to fix the issue. I can type now with all four combinations. But I can't guarantee that the code is correct ;)
