### ISSUE TITLE
hstr 2.2.0-2: Fedora 31

### ISSUE THREAD

**Issue by dirkduplooy** [dvorka/hstr#384]
I tried to install hstr-2.2.0-2.x86_64.rpm from the Github releases page.

When I used sudo rpm -Uvh ./hstr-2.2.0-2.x86_64.rpm -y I got rpm: -y: unknown option. 

So I dropped the -y option

Then I got this error:

error: Failed dependencies:
libreadline.so.7()(64bit) is needed by hstr-2.2.0-2.x86_64

is there a specific package I need to install for this dependency?

**Comment by dvorka** [comment]
Oh, thank you for letting me know Dirk! Can you please check which `readline` version do you have in your system? For instance try `locate libreadline.so` or `find /lib -name "libreadline.so.*"` and share the output here. I think that I would be able to build RPM w/ the right dependency.

Once I have a bit of time, I will setup `Fedore 31` virtual machine and try it there.

@dirkduplooy thanks again!

**Comment by dirkduplooy** [comment]
@dvorka Thanks for your fast feedback, the output is as follows:
locate libreadline.so

/usr/lib64/libreadline.so.5

/usr/lib64/libreadline.so.5.2

/usr/lib64/libreadline.so.8

/usr/lib64/libreadline.so.8.0

**Comment by dvorka** [comment]
BTW, if you would be OK with older `HSTR` version (`1.22`), you can install it on Fedora 31 with:
```
sudo dnf install hstr
```

**Comment by dvorka** [comment]
@dirkduplooy I just build `RPM` on `Fedora 31`:
1. Please download `hstr-2.2.0-2-fedora-31.x86_64.rpm
from https://github.com/dvorka/hstr/releases/tag/2.2
2. Install it using `sudo dnf install ./hstr-2.2.0-2-fedora-31.x86_64.rpm`

**Comment by dirkduplooy** [comment]
hh --version
hstr version "2.2.0" (2019-12-21T08:47:00)
 Thanks @dvorka working like a charm :-)
