### ISSUE TITLE
zsh show-configuration not correct in README

### ISSUE THREAD

**Issue by z7z8th** [dvorka/hstr#394]
```sh
# bash
hstr --show-configuration >> ~/.bashrc

# zsh
hstr --show-configuration >> ~/.zshrc
```

Should be 
`hstr --show-zsh-configuration >> ~/.zshrc`

**Comment by dvorka** [comment]
`hstr` actually tries to be smart and detect shell. If the detection fails, `--show-zsh-configuration` ensures `zsh` specific installation.
