### ISSUE TITLE
Spelling error in manpage file.

### ISSUE THREAD

**Issue by epsilon77** [dvorka/hstr#398]
HI!

The manpage has a spelling error.

--- a/man/hstr.1
+++ b/man/hstr.1
@@ -9,7 +9,7 @@
 for commands used in the past. By default it parses .bash-history
 file that is filtered as you type a command substring. Commands 
 are not just filtered, but also ordered by a ranking algorithm
-that considers number of occurences, length and timestamp. 
+that considers number of occurrences, length and timestamp. 
 Favorite and frequently used commands can be bookmarked. In addition
 \fBhstr\fR allows removal of commands from history - for instance with a typo 
 or with a sensitive content.

Thanks!

**Comment by dvorka** [comment]
Fixed by 4c7db9f - will be released with HSTR 2.6
