### ISSUE TITLE
Option to show context (N lines before & after)

### ISSUE THREAD

**Issue by y20zhang-nokia** [dvorka/hstr#406]
It'd be nice to have an option to get the context for a command.
For instance, I ran some commands to get some processes to kill. I only remember I ran the kill command but only need the command before kill.
I know I could do `history | grep -B 3 -A 3 "kill"`, and I think that'd a nice enhancement.

**Comment by Zackhardtoname** [comment]
Please see @407. (used wrong account when opening this one)

**Comment by y20zhang-nokia** [comment]
Please see @407. (used wrong account when opening this one)
