### ISSUE TITLE
Is there a way to sort by history (default), instead of by ranking (default)?

### ISSUE THREAD

**Issue by evandrix** [dvorka/hstr#415]

**Comment by dvorka** [comment]
@evandrix just configure `HSTR` using:
```
export HSTR_CONFIG=raw-history-view,hicolor
```
Check `man hstr` for more settings and details. You may want to add command from above to `.bashrc`/`.zshrc`.

**Comment by evandrix** [comment]
holy shit, nice! thanks, it works!
