### ISSUE TITLE
Windows port or alternative?

### ISSUE THREAD

**Issue by bodgergely** [dvorka/hstr#433]
I'd love to use it on Windows without WSL or Cygwin.
Was there a request or an effort to make hstr platform independent, meaning a Windows port?
I can see the project depends on ncurses that needs an equivalent on Windows.

Otherwise, can someone recommend something akin to hstr in the Windows world?

**Comment by ChristopherHaws** [comment]
For powershell, PSReadLine will give you similar results. This is my config:

```powershell
Import-Module PSReadLine

Set-PSReadLineOption -PredictionSource History
Set-PSReadLineOption -PredictionViewStyle ListView
Set-PSReadLineOption -EditMode Windows
```
