### ISSUE TITLE
sort by name and delete duplicates and write back to history!

### ISSUE THREAD

**Issue by OneOfLosers** [dvorka/hstr#438]
Hello,

it it possible to implement this  as a one key function?

Sorting they history means "killing what happend before" any way, so if one wants that there is no need to go back but to optimize, and by that mean you do not need duplicates and no duplicates means lesser space in history and faster searches.

Possible?

(36 years+ after invention of unixoids ..., really!?! .... that means "except this developer" unixer are also not smarter than MS-Gates not implemented that function in bash in these "100" years :P )

Still best thanks for this smart software! Be sure  MS don't  stealing the idea for PS (vomit) sry ....

**Comment by zvezdochiot** [comment]
Hi @OneOfLosers .

`hstr` does not manage history, but makes search through it interactive, works with what is. Your request is inappropriate.

**Comment by dvorka** [comment]
@OneOfLosers in addition to ^ answer from @OneOfLosers:

* `HSTR` can show dedup history - just use <kbd>Ctrl-w</kbd> to rate view and check `view:history` in status view - this is exactly what you are asking for
* all history items are used by heuristics which suggests commands in `HSTR` - more entries (recently), higher position in the recent list
* `HSTR` cannot  persist dedup history as it would break expected content of history file and potentially screw other commands and application of the system

Hope it helped!
