### ISSUE TITLE
Installation Steps does not function in Linux Min 20.3

### ISSUE THREAD

**Issue by OneOfLosers** [dvorka/hstr#446]
sudo apt install hstr does not function!

Installation steps for Ubuntu in Mint does not function!

Can you make any packages that automatically invoke the Min-Installer?

How does one his software spread if it is not noob-friendly???

**Comment by dvorka** [comment]
@OneOfLosers if package for `apt` is not available, use one of the options from below:

* install compatible `.deb` from https://pkgs.org/search/?q=hstr
* use `.deb` from compatible Debian distribution
* install my PPA and update HSTR from there (if compatible)
* build from the source

Thank you for your interest in `HSTR`!
