### ISSUE TITLE
Error installing hstr on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by BekaOkromchedlidze** [dvorka/hstr#460]
Hi, 
I am having trouble installing hstr on Ubuntu 20.04.5 LTS. Please see screenshot below.

![image](https://user-images.githubusercontent.com/45874523/188611927-921eefc2-5a99-4070-9533-ab7276ec1925.png)

**Comment by dvorka** [comment]
I added 2.6.0 release for Ubuntu 20.04 (Focal Fossa) https://launchpad.net/~ultradvorka/+archive/ubuntu/ppa/+packages
