### ISSUE TITLE
Latest release missing release tarball

### ISSUE THREAD

**Issue by herbygillot** [dvorka/hstr#474]
Hello, the latest release version, `2.6`, seems to be missing the `hstr-2.6.0-tarball.tgz`: https://github.com/dvorka/hstr/releases/tag/2.6

**Comment by ryandesign** [comment]
Hello?

**Comment by dvorka** [comment]
@herbygillot I apologize for not attaching the tarball and the delayed response - it's there (generated for `2.6.0` development branch: https://github.com/dvorka/hstr/releases/tag/2.6 Thank you for letting me know!
