### ISSUE TITLE
Issues with new ARCH Linux kernel 6.2.8-arch1-1, works well with stable kernel.

### ISSUE THREAD

**Issue by MKastuv** [dvorka/hstr#482]
When I open select the command from hstr, it won't paste it in the terminal. I am using 6.2.8-arch1-1. Works well when I boot in LTS kernel. Not sure what broke this up. I was checking out couple new kernel upgrades and it has been failing in all new after 6.2.7.

**Comment by dvorka** [comment]
@MKastuv there is a problem w/ new kernels - please see #478. I work on the fix...

**Comment by dvorka** [comment]
Fixed by aa14f032d4f39b38d7c7ccc042f18400760a3bd7 - see #478 for more details.
