### ISSUE TITLE
Incorrect links in INSTALLATION.md

### ISSUE THREAD

**Issue by albert-github** [dvorka/hstr#484]
https://github.com/dvorka/hstr/blob/f370a80e3d76cd74d0f3064e32ef86b0339a402f/INSTALLATION.md?plain=1#L41-L42

Links should be corrected to (see the "chain" in front of the paragraph on GitHub):
```
* [HSTR 1.x to 2.x](#hstr-1-x-to-2-x-from-hh-to-hstr)
* [HSTR 2.x to 3.x](#hstr-2-x-to-3-x-ioctl--tiocsti)
```

**Comment by dvorka** [comment]
Fixed by [e1ba44a](https://github.com/dvorka/hstr/commit/e1ba44a4e83c564a14232457b70df1a1d93c7309)
