### ISSUE TITLE
History shows some letters blanked out 

### ISSUE THREAD

**Issue by monochromec** [dvorka/hstr#498]
When invoking the history with CTRL-R and starting a search by typing a few letters, some entries show missing letters. Only when the line is actually selected by corresponding cursor movements, these missing letters are displayed using reverse video as expected.

OS: OSX 13.5.1
hstr version: 3.1
readline version: 8.2.1
ncurses version: 6.4

This can issue can be reproduced independently of installation via homebrew or compilation from the source code. More than happy to provide additional information if required.

**Comment by xidiot** [comment]
Please check if my issue is same like yours - https://github.com/dvorka/hstr/issues/497

**Comment by monochromec** [comment]
The symptoms are different but the RC may be the same (as the symptoms start to occur after the upgrade to OSX 13.5). Furthered by the interesting fact that the first video supposedly shows the access to a remote system (Linux in this case) but the issue still persist locally, so I suspect the RC lying below ncurses (as I can reproduce this in both the console app and iTerm2). 

Would it make sense to send a request back to Apple via the Feedback Assistant?!?

**Comment by monochromec** [comment]
Feedback has been submitted to Apple as FB13015582. Let's see what comes out of it.

**Comment by monochromec** [comment]
Updating to Sonoma apparently solved the issue.

**Comment by fharper** [comment]
Just updated to Sonoma, and I can confirm it also fixed it for me!
