### ISSUE TITLE
doc/ with MD: regexp, favorites, configuration, installation, ...

### ISSUE THREAD

**Issue by dvorka** [dvorka/hstr#88]
Make introduction on the home page much more brief and move detailed documentation to doc/

**Comment by InfernoZeus** [comment]
Adding a list of available `HH_CONFIG` values would be useful. I had to search through the code to find that `export HH_CONFIG=keywords` was already supported :)

**Comment by dvorka** [comment]
regexp, substring and keywords not in CONFIGURATION.md and keywords not in man page.
