### ISSUE TITLE
Compilation under Cygwin: TIOCSTI undeclared

### ISSUE THREAD

**Issue by robbielj** [dvorka/hstr#97]
Hello,

I tried to compile and use hstr under cygwin environment. During the compiling, there was an error about undeclared TIOCSTI. I explicitly defined it as 0x5412, according to search results on similar issue. Then compiling went fine. 

Key bindings of hstr seems to function normally, except for TAB, which doesn't select and return the highlighted item.

Is there a solution to this issue?

**Comment by dvorka** [comment]
#IFDEF + compilation under cygwin.

**Comment by beelsr** [comment]
i had the same problem. current cygwin 2.whatever.

**method:**
git clone ....
cd hstr
cd ./dist && ./1-dist.sh && cd ..
./configure
-- all OK to this point --
make dies with basically the above error:

-----
make[1]: Entering directory '/mnt/c/Apps/Cygwin/home/Spiff/hstr/src'
gcc -DPACKAGE_NAME=\"hh\" -DPACKAGE_TARNAME=\"hh\" -DPACKAGE_VERSION=\"1.18\" -DPACKAGE_STRING=\"hh\ 1.18\" -DPACKAGE_BUGREPORT=\"martin.dvorak@mindforger.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"hh\" -DVERSION=\"1.18\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBNCURSESW=1 -DHAVE_LIBM=1 -DHAVE_LIBREADLINE=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MEMSET=1 -DHAVE_STRDUP=1 -DHAVE_STRSTR=1 -I.    --pedantic -Wall -std=c99 -O2 -g -O2 -MT hstr_utils.o -MD -MP -MF .deps/hstr_utils.Tpo -c -o hstr_utils.o hstr_utils.c
hstr_utils.c: In function ‘tiocsti’:
hstr_utils.c:72:18: error: ‘TIOCSTI’ undeclared (first use in this function)
         ioctl(0, TIOCSTI, &buf[i]);
                  ^
hstr_utils.c:72:18: note: each undeclared identifier is reported only once for each function it appears in
hstr_utils.c: In function ‘fill_terminal_input’:
hstr_utils.c:85:22: error: ‘TIOCSTI’ undeclared (first use in this function)
             ioctl(0, TIOCSTI, c);
                      ^
Makefile:363: recipe for target 'hstr_utils.o' failed
make[1]: *** [hstr_utils.o] Error 1
make[1]: Leaving directory '/mnt/c/Apps/Cygwin/home/Spiff/hstr/src'
Makefile:333: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

----

I see the #IFDEF in hstr.c and the unsigned mod in hstr_utils, as above but that didn't fix it for me.

**To fix**
I added #define TIOCSTI 0x5412 explicitly in hstr_utils and was able to get hh to compile and run. Seems make is grabbing hstr_utils.c first and can't backtrack to the define in hstr.c

**Comment by dvorka** [comment]
Thank you for the report and fix suggestion - I will do my best to reproduce this one and make sure the fix works.

**Comment by 0-sv** [comment]
I have the same problem compiling on cygwin (feel free to ask for additional details). Error message:

```
$ make
Making all in src
make[1]: Entering directory '/home/sebastiaan.verbe_nsp/hstr/src'
source='hstr_utils.c' object='hstr_utils.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
gcc -DPACKAGE_NAME=\"hstr\" -DPACKAGE_TARNAME=\"hstr\" -DPACKAGE_VERSION=\"3.0.0\" -DPACKAGE_STRING=\"hstr\ 3.0.0\" -DPACKAGE_BUGREPORT=\"martin.dvorak@mindforger.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"hstr\" -DVERSION=\"3.0.0\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_LIBNCURSESW=1 -DHAVE_LIBM=1 -DHAVE_LIBREADLINE=1 -DHAVE__BOOL=1 -DHAVE_MALLOC=1 -DHAVE_MEMSET=1 -DHAVE_STRDUP=1 -DHAVE_STRSTR=1 -I.    --pedantic -Wall -std=c99 -O2 -g -O2 -c -o hstr_utils.o hstr_utils.c
hstr_utils.c: In function ‘fill_terminal_input’:
hstr_utils.c:170:26: error: ‘TIOCSTI’ undeclared (first use in this function)
  170 |                 ioctl(0, TIOCSTI, c);
      |                          ^~~~~~~
hstr_utils.c:170:26: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:413: hstr_utils.o] Error 1
make[1]: Leaving directory '/home/sebastiaan.verbe_nsp/hstr/src'
make: *** [Makefile:407: all-recursive] Error 1

```

Fixed it by placing `#define TIOCSTI 0x5412` in `hstr_utils.c`
